"""initial schema

Revision ID: ecb2d635a222
Revises: 
Create Date: 2025-10-29 13:19:51.901313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecb2d635a222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comicsummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('villain_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superhero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('eye_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hair_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('powers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strength_level', sa.Integer(), nullable=True),
    sa.Column('speed_level', sa.Integer(), nullable=True),
    sa.Column('durability_level', sa.Integer(), nullable=True),
    sa.Column('intelligence_level', sa.Integer(), nullable=True),
    sa.Column('weaknesses', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strengths', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superhero_hero_name'), 'superhero', ['hero_name'], unique=False)
    op.create_table('supervillain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('villain_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('eye_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hair_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('powers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strength_level', sa.Integer(), nullable=True),
    sa.Column('speed_level', sa.Integer(), nullable=True),
    sa.Column('durability_level', sa.Integer(), nullable=True),
    sa.Column('intelligence_level', sa.Integer(), nullable=True),
    sa.Column('weaknesses', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strengths', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervillain_villain_name'), 'supervillain', ['villain_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervillain_villain_name'), table_name='supervillain')
    op.drop_table('supervillain')
    op.drop_index(op.f('ix_superhero_hero_name'), table_name='superhero')
    op.drop_table('superhero')
    op.drop_table('comicsummary')
    # ### end Alembic commands ###
